// Code generated by acp-go-generator; DO NOT EDIT.

package acp

// NewAuthMethodEnvVar constructs a AuthMethod using the 'env_var' variant.
func NewAuthMethodEnvVar(id AuthMethodId, name string, vars []AuthEnvVar) AuthMethod {
	return AuthMethod{EnvVar: &AuthMethodEnvVarInline{
		Id:   id,
		Name: name,
		Type: "env_var",
		Vars: vars,
	}}
}

// NewAuthMethodTerminal constructs a AuthMethod using the 'terminal' variant.
func NewAuthMethodTerminal(id AuthMethodId, name string) AuthMethod {
	return AuthMethod{Terminal: &AuthMethodTerminalInline{
		Id:   id,
		Name: name,
		Type: "terminal",
	}}
}

// NewAuthMethodAgent constructs a AuthMethod using the ” variant.
func NewAuthMethodAgent(id AuthMethodId, name string) AuthMethod {
	return AuthMethod{Agent: &AuthMethodAgent{
		Id:   id,
		Name: name,
	}}
}

// NewAvailableCommandInputUnstructured constructs a AvailableCommandInput using the ” variant.
func NewAvailableCommandInputUnstructured(hint string) AvailableCommandInput {
	return AvailableCommandInput{Unstructured: &UnstructuredCommandInput{Hint: hint}}
}

// NewEmbeddedResourceResourceTextResourceContents constructs a EmbeddedResourceResource using the ” variant.
func NewEmbeddedResourceResourceTextResourceContents(text string, uri string) EmbeddedResourceResource {
	return EmbeddedResourceResource{TextResourceContents: &TextResourceContents{
		Text: text,
		Uri:  uri,
	}}
}

// NewEmbeddedResourceResourceBlobResourceContents constructs a EmbeddedResourceResource using the ” variant.
func NewEmbeddedResourceResourceBlobResourceContents(blob string, uri string) EmbeddedResourceResource {
	return EmbeddedResourceResource{BlobResourceContents: &BlobResourceContents{
		Blob: blob,
		Uri:  uri,
	}}
}

// NewMcpServerHttp constructs a McpServer using the 'http' variant.
func NewMcpServerHttp(headers []HttpHeader, name string, url string) McpServer {
	return McpServer{Http: &McpServerHttpInline{
		Headers: headers,
		Name:    name,
		Type:    "http",
		Url:     url,
	}}
}

// NewMcpServerSse constructs a McpServer using the 'sse' variant.
func NewMcpServerSse(headers []HttpHeader, name string, url string) McpServer {
	return McpServer{Sse: &McpServerSseInline{
		Headers: headers,
		Name:    name,
		Type:    "sse",
		Url:     url,
	}}
}

// NewMcpServerAcp constructs a McpServer using the 'acp' variant.
func NewMcpServerAcp(name string, serverId McpServerAcpId) McpServer {
	return McpServer{Acp: &McpServerAcpInline{
		Name:     name,
		ServerId: serverId,
		Type:     "acp",
	}}
}

// NewMcpServerStdio constructs a McpServer using the ” variant.
func NewMcpServerStdio(args []string, command string, env []EnvVariable, name string) McpServer {
	return McpServer{Stdio: &McpServerStdio{
		Args:    args,
		Command: command,
		Env:     env,
		Name:    name,
	}}
}

// NewPlanUpdateContentItems constructs a PlanUpdateContent using the 'items' variant.
func NewPlanUpdateContentItems(entries []PlanEntry, planId PlanId) PlanUpdateContent {
	return PlanUpdateContent{Items: &PlanUpdateContentItems{
		Entries: entries,
		PlanId:  planId,
		Type:    "items",
	}}
}

// NewPlanUpdateContentFile constructs a PlanUpdateContent using the 'file' variant.
func NewPlanUpdateContentFile(planId PlanId, uri string) PlanUpdateContent {
	return PlanUpdateContent{File: &PlanUpdateContentFile{
		PlanId: planId,
		Type:   "file",
		Uri:    uri,
	}}
}

// NewPlanUpdateContentMarkdown constructs a PlanUpdateContent using the 'markdown' variant.
func NewPlanUpdateContentMarkdown(content string, planId PlanId) PlanUpdateContent {
	return PlanUpdateContent{Markdown: &PlanUpdateContentMarkdown{
		Content: content,
		PlanId:  planId,
		Type:    "markdown",
	}}
}

// NewRequestPermissionOutcomeCancelled constructs a RequestPermissionOutcome using the 'cancelled' variant.
func NewRequestPermissionOutcomeCancelled() RequestPermissionOutcome {
	return RequestPermissionOutcome{Cancelled: &RequestPermissionOutcomeCancelled{Outcome: "cancelled"}}
}

// NewRequestPermissionOutcomeSelected constructs a RequestPermissionOutcome using the 'selected' variant.
func NewRequestPermissionOutcomeSelected(optionId PermissionOptionId) RequestPermissionOutcome {
	return RequestPermissionOutcome{Selected: &RequestPermissionOutcomeSelected{
		OptionId: optionId,
		Outcome:  "selected",
	}}
}

// NewSessionConfigOptionSelect constructs a SessionConfigOption using the 'select' variant.
func NewSessionConfigOptionSelect(currentValue SessionConfigValueId, id SessionConfigId, name string, options SessionConfigSelectOptions) SessionConfigOption {
	return SessionConfigOption{Select: &SessionConfigOptionSelect{
		CurrentValue: currentValue,
		Id:           id,
		Name:         name,
		Options:      options,
		Type:         "select",
	}}
}

// NewSessionConfigOptionBoolean constructs a SessionConfigOption using the 'boolean' variant.
func NewSessionConfigOptionBoolean(currentValue bool, id SessionConfigId, name string) SessionConfigOption {
	return SessionConfigOption{Boolean: &SessionConfigOptionBoolean{
		CurrentValue: currentValue,
		Id:           id,
		Name:         name,
		Type:         "boolean",
	}}
}

// NewSetSessionConfigOptionRequestBoolean constructs a SetSessionConfigOptionRequest using the 'boolean' variant.
func NewSetSessionConfigOptionRequestBoolean(configId SessionConfigId, sessionId SessionId, value bool) SetSessionConfigOptionRequest {
	return SetSessionConfigOptionRequest{Boolean: &SetSessionConfigOptionBoolean{
		ConfigId:  configId,
		SessionId: sessionId,
		Type:      "boolean",
		Value:     value,
	}}
}

// NewSetSessionConfigOptionRequestValueId constructs a SetSessionConfigOptionRequest using the ” variant.
func NewSetSessionConfigOptionRequestValueId(configId SessionConfigId, sessionId SessionId, value SessionConfigValueId) SetSessionConfigOptionRequest {
	return SetSessionConfigOptionRequest{ValueId: &SetSessionConfigOptionValueId{
		ConfigId:  configId,
		SessionId: sessionId,
		Value:     value,
	}}
}

// NewUnstableCreateElicitationRequestFormSession constructs a UnstableCreateElicitationRequest using the 'form' variant.
func NewUnstableCreateElicitationRequestFormSession(message string, requestedSchema UnstableElicitationSchema, sessionId SessionId) UnstableCreateElicitationRequest {
	return UnstableCreateElicitationRequest{FormSession: &UnstableCreateElicitationFormSession{
		Message:         message,
		Mode:            "form",
		RequestedSchema: requestedSchema,
		SessionId:       sessionId,
	}}
}

// NewUnstableCreateElicitationRequestFormRequest constructs a UnstableCreateElicitationRequest using the 'form' variant.
func NewUnstableCreateElicitationRequestFormRequest(message string, requestId RequestId, requestedSchema UnstableElicitationSchema) UnstableCreateElicitationRequest {
	return UnstableCreateElicitationRequest{FormRequest: &UnstableCreateElicitationFormRequest{
		Message:         message,
		Mode:            "form",
		RequestId:       requestId,
		RequestedSchema: requestedSchema,
	}}
}

// NewUnstableCreateElicitationRequestUrlSession constructs a UnstableCreateElicitationRequest using the 'url' variant.
func NewUnstableCreateElicitationRequestUrlSession(elicitationId UnstableElicitationId, message string, sessionId SessionId, url string) UnstableCreateElicitationRequest {
	return UnstableCreateElicitationRequest{UrlSession: &UnstableCreateElicitationUrlSession{
		ElicitationId: elicitationId,
		Message:       message,
		Mode:          "url",
		SessionId:     sessionId,
		Url:           url,
	}}
}

// NewUnstableCreateElicitationRequestUrlRequest constructs a UnstableCreateElicitationRequest using the 'url' variant.
func NewUnstableCreateElicitationRequestUrlRequest(elicitationId UnstableElicitationId, message string, requestId RequestId, url string) UnstableCreateElicitationRequest {
	return UnstableCreateElicitationRequest{UrlRequest: &UnstableCreateElicitationUrlRequest{
		ElicitationId: elicitationId,
		Message:       message,
		Mode:          "url",
		RequestId:     requestId,
		Url:           url,
	}}
}

// NewUnstableCreateElicitationRequestOtherSession constructs a UnstableCreateElicitationRequest using the ” variant.
func NewUnstableCreateElicitationRequestOtherSession(message string, mode string, sessionId SessionId) UnstableCreateElicitationRequest {
	return UnstableCreateElicitationRequest{OtherSession: &UnstableCreateElicitationOtherSession{
		Message:   message,
		Mode:      mode,
		SessionId: sessionId,
	}}
}

// NewUnstableCreateElicitationRequestOtherRequest constructs a UnstableCreateElicitationRequest using the ” variant.
func NewUnstableCreateElicitationRequestOtherRequest(message string, mode string, requestId RequestId) UnstableCreateElicitationRequest {
	return UnstableCreateElicitationRequest{OtherRequest: &UnstableCreateElicitationOtherRequest{
		Message:   message,
		Mode:      mode,
		RequestId: requestId,
	}}
}

// NewUnstableCreateElicitationResponseAccept constructs a UnstableCreateElicitationResponse using the 'accept' variant.
func NewUnstableCreateElicitationResponseAccept() UnstableCreateElicitationResponse {
	return UnstableCreateElicitationResponse{Accept: &UnstableCreateElicitationAccept{Action: "accept"}}
}

// NewUnstableCreateElicitationResponseDecline constructs a UnstableCreateElicitationResponse using the 'decline' variant.
func NewUnstableCreateElicitationResponseDecline() UnstableCreateElicitationResponse {
	return UnstableCreateElicitationResponse{Decline: &UnstableCreateElicitationDecline{Action: "decline"}}
}

// NewUnstableCreateElicitationResponseCancel constructs a UnstableCreateElicitationResponse using the 'cancel' variant.
func NewUnstableCreateElicitationResponseCancel() UnstableCreateElicitationResponse {
	return UnstableCreateElicitationResponse{Cancel: &UnstableCreateElicitationCancel{Action: "cancel"}}
}

// NewUnstableCreateElicitationResponseOther constructs a UnstableCreateElicitationResponse using the ” variant.
func NewUnstableCreateElicitationResponseOther(action string) UnstableCreateElicitationResponse {
	return UnstableCreateElicitationResponse{Other: &UnstableCreateElicitationOther{Action: action}}
}

// NewUnstableElicitationFormModeSession constructs a UnstableElicitationFormMode using the ” variant.
func NewUnstableElicitationFormModeSession(requestedSchema UnstableElicitationSchema, sessionId SessionId) UnstableElicitationFormMode {
	return UnstableElicitationFormMode{Session: &UnstableElicitationFormModeSession{
		RequestedSchema: requestedSchema,
		SessionId:       sessionId,
	}}
}

// NewUnstableElicitationFormModeRequest constructs a UnstableElicitationFormMode using the ” variant.
func NewUnstableElicitationFormModeRequest(requestId RequestId, requestedSchema UnstableElicitationSchema) UnstableElicitationFormMode {
	return UnstableElicitationFormMode{Request: &UnstableElicitationFormModeRequest{
		RequestId:       requestId,
		RequestedSchema: requestedSchema,
	}}
}

// NewUnstableElicitationUrlModeSession constructs a UnstableElicitationUrlMode using the ” variant.
func NewUnstableElicitationUrlModeSession(elicitationId UnstableElicitationId, sessionId SessionId, url string) UnstableElicitationUrlMode {
	return UnstableElicitationUrlMode{Session: &UnstableElicitationUrlModeSession{
		ElicitationId: elicitationId,
		SessionId:     sessionId,
		Url:           url,
	}}
}

// NewUnstableElicitationUrlModeRequest constructs a UnstableElicitationUrlMode using the ” variant.
func NewUnstableElicitationUrlModeRequest(elicitationId UnstableElicitationId, requestId RequestId, url string) UnstableElicitationUrlMode {
	return UnstableElicitationUrlMode{Request: &UnstableElicitationUrlModeRequest{
		ElicitationId: elicitationId,
		RequestId:     requestId,
		Url:           url,
	}}
}

// NewUnstableMcpServerHttp constructs a UnstableMcpServer using the 'http' variant.
func NewUnstableMcpServerHttp(headers []HttpHeader, name string, url string) UnstableMcpServer {
	return UnstableMcpServer{Http: &UnstableMcpServerHttp{
		Headers: headers,
		Name:    name,
		Type:    "http",
		Url:     url,
	}}
}

// NewUnstableMcpServerSse constructs a UnstableMcpServer using the 'sse' variant.
func NewUnstableMcpServerSse(headers []HttpHeader, name string, url string) UnstableMcpServer {
	return UnstableMcpServer{Sse: &UnstableMcpServerSse{
		Headers: headers,
		Name:    name,
		Type:    "sse",
		Url:     url,
	}}
}

// NewUnstableMcpServerAcp constructs a UnstableMcpServer using the 'acp' variant.
func NewUnstableMcpServerAcp(name string, serverId UnstableMcpServerAcpId) UnstableMcpServer {
	return UnstableMcpServer{Acp: &UnstableMcpServerAcpInline{
		Name:     name,
		ServerId: serverId,
		Type:     "acp",
	}}
}

// NewUnstableMcpServerStdio constructs a UnstableMcpServer using the ” variant.
func NewUnstableMcpServerStdio(args []string, command string, env []EnvVariable, name string) UnstableMcpServer {
	return UnstableMcpServer{Stdio: &McpServerStdio{
		Args:    args,
		Command: command,
		Env:     env,
		Name:    name,
	}}
}

// NewUnstableNesSuggestionEdit constructs a UnstableNesSuggestion using the 'edit' variant.
func NewUnstableNesSuggestionEdit(edits []UnstableNesTextEdit, id UnstableNesSuggestionId, uri string) UnstableNesSuggestion {
	return UnstableNesSuggestion{Edit: &UnstableNesSuggestionEdit{
		Edits: edits,
		Id:    id,
		Kind:  "edit",
		Uri:   uri,
	}}
}

// NewUnstableNesSuggestionJump constructs a UnstableNesSuggestion using the 'jump' variant.
func NewUnstableNesSuggestionJump(id UnstableNesSuggestionId, position UnstablePosition, uri string) UnstableNesSuggestion {
	return UnstableNesSuggestion{Jump: &UnstableNesSuggestionJump{
		Id:       id,
		Kind:     "jump",
		Position: position,
		Uri:      uri,
	}}
}

// NewUnstableNesSuggestionRename constructs a UnstableNesSuggestion using the 'rename' variant.
func NewUnstableNesSuggestionRename(id UnstableNesSuggestionId, newName string, position UnstablePosition, uri string) UnstableNesSuggestion {
	return UnstableNesSuggestion{Rename: &UnstableNesSuggestionRename{
		Id:       id,
		Kind:     "rename",
		NewName:  newName,
		Position: position,
		Uri:      uri,
	}}
}

// NewUnstableNesSuggestionSearchAndReplace constructs a UnstableNesSuggestion using the 'searchAndReplace' variant.
func NewUnstableNesSuggestionSearchAndReplace(id UnstableNesSuggestionId, replace string, search string, uri string) UnstableNesSuggestion {
	return UnstableNesSuggestion{SearchAndReplace: &UnstableNesSuggestionSearchAndReplace{
		Id:      id,
		Kind:    "searchAndReplace",
		Replace: replace,
		Search:  search,
		Uri:     uri,
	}}
}
