package emit

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/coder/acp-go-sdk/cmd/generate/internal/ir"
	"github.com/coder/acp-go-sdk/cmd/generate/internal/load"
	"github.com/coder/acp-go-sdk/cmd/generate/internal/util"
)

// WriteHelpersJen emits go/helpers_gen.go with small constructor helpers
// for common union variants and a Ptr generic helper.
func WriteHelpersJen(outDir string, schema *load.Schema, _ *load.Meta) error {
	f := NewFile("acp")
	f.HeaderComment("Code generated by acp-go-generator; DO NOT EDIT.")

	// Schema-driven generic helpers: New<Union><Variant>(required fields only)
	// Track used type names to match the types emitter's naming (generateNestedTypeName).
	usedTypeNames := make(map[string]bool, len(schema.Defs))
	for k := range schema.Defs {
		usedTypeNames[k] = true
	}

	// Iterate definitions deterministically
	keys := make([]string, 0, len(schema.Defs))
	for k := range schema.Defs {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, name := range keys {
		def := schema.Defs[name]
		if def == nil || def.DocsIgnore {
			continue
		}
		unionDefs := def.OneOf
		if len(unionDefs) == 0 {
			unionDefs = def.AnyOf
		}
		if len(unionDefs) == 0 {
			continue
		}
		// Skip string-const unions
		if isStringConstUnion(def) || isOpenStringEnum(def) {
			continue
		}
		// Skip generating New... helpers for unions that have stable, static helpers
		// implemented in go/helpers.go.
		switch name {
		case "ContentBlock", "ToolCallContent", "SessionUpdate":
			continue
		}
		// Build variant info using the same logic as the types emitter (emitUnion)
		// to ensure type names match exactly.
		type vinfo struct {
			fieldName string
			typeName  string
			discKey   string
			discValue string
			required  []string
			props     map[string]*load.Definition
		}
		alternatives := expandUnionAlternatives(schema, unionDefs)
		discKey := ""
		// Use schema's explicit discriminator if available (matching types emitter)
		if def.Discriminator != nil {
			discKey = def.Discriminator.PropertyName
		}
		// Fallback: discover discriminator key by scanning for const properties
		if discKey == "" {
			for _, alternative := range alternatives {
				v := alternative.def
				if v == nil {
					continue
				}
				for k, pd := range v.Properties {
					if pd != nil && pd.Const != nil {
						discKey = k
						break
					}
				}
				if discKey != "" {
					break
				}
			}
		}
		variants := []vinfo{}
		for idx, alternative := range alternatives {
			v := alternative.def
			if v == nil || ir.PrimaryType(v) != "object" {
				continue
			}
			ref := alternative.ref
			if len(def.Properties) > 0 {
				ref = ""
			}

			// Compute type name matching the types emitter (emitUnion)
			tname := ""
			if ref != "" && strings.HasPrefix(ref, "#/$defs/") {
				tname = ref[len("#/$defs/"):]
			} else if v.Title != "" {
				tname = generateNestedTypeName(name, v.Title+alternative.nameSuffix, usedTypeNames)
				usedTypeNames[tname] = true
			} else {
				if discKey != "" {
					if pd := v.Properties[discKey]; pd != nil && pd.Const != nil {
						s := fmt.Sprint(pd.Const) + alternative.nameSuffix
						tname = generateNestedTypeName(name, s, usedTypeNames)
						usedTypeNames[tname] = true
					}
				}
				if tname == "" {
					tname = name + fmt.Sprintf("Variant%d", idx+1)
					usedTypeNames[tname] = true
				}
			}
			tname = util.ToExportedField(tname)

			// Derive field name with same priority as types emitter
			fieldName := ""
			dv := ""
			if discKey != "" {
				if pd := v.Properties[discKey]; pd != nil && pd.Const != nil {
					s := fmt.Sprint(pd.Const)
					fieldName = util.ToExportedField(s + alternative.nameSuffix)
					dv = s
				}
			}
			if fieldName == "" && v.Title != "" {
				fieldName = util.ToExportedField(v.Title + alternative.nameSuffix)
			}
			if fieldName == "" {
				fieldName = util.ToExportedField(tname)
			}
			// Merge parent/shared properties and required fields into each concrete
			// alternative so constructor signatures match the flattened wire type.
			props := make(map[string]*load.Definition, len(def.Properties)+len(v.Properties))
			for propertyName, property := range def.Properties {
				props[propertyName] = property
			}
			for propertyName, property := range v.Properties {
				props[propertyName] = property
			}
			req := mergeRequired(v.Required, def.Required)
			variants = append(variants, vinfo{fieldName: fieldName, typeName: tname, discKey: discKey, discValue: dv, required: req, props: props})
		}
		// Emit helper per variant: func New<Union><FieldName>(...) <Union>
		for _, vi := range variants {
			// params: all required props except const discriminator
			params := []Code{}
			assigns := Dict{}
			for _, rk := range vi.required {
				if rk == vi.discKey && vi.discValue != "" {
					continue
				}
				pd := vi.props[rk]
				if pd == nil {
					continue
				}
				// build param using lower-cased name
				pname := rk
				// field id for struct literal
				field := util.ToExportedField(rk)
				params = append(params, Id(pname).Add(jenTypeFor(pd)))
				assigns[Id(field)] = Id(pname)
			}
			// include const discriminant if present and field exists on struct
			if vi.discKey != "" && vi.discValue != "" {
				assigns[Id(util.ToExportedField(vi.discKey))] = Lit(vi.discValue)
			}
			// Construct variant literal and wrap
			f.Comment(fmt.Sprintf("New%s%s constructs a %s using the '%s' variant.", name, vi.fieldName, name, vi.discValue))
			f.Func().Id("New" + name + vi.fieldName).Params(params...).Id(name).Block(
				Return(
					Id(name).Values(Dict{
						Id(vi.fieldName): Op("&").Id(vi.typeName).Values(assigns),
					}),
				),
			)
			f.Line()
		}
	}

	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(outDir, "helpers_gen.go"), buf.Bytes(), 0o644)
}
